# Generated by Django 4.1.2 on 2022-10-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_client_alter_invoice_id_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_product',
            field=models.ImageField(default='media/images', upload_to='media/images'),
        ),
    ]
