# Generated by Django 4.1.2 on 2022-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_photo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_product',
            field=models.ImageField(default='media/images/', upload_to='media/images/'),
        ),
    ]
