# Generated by Django 4.1.2 on 2022-10-27 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_alter_product_photo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
