# Generated by Django 4.1.2 on 2022-11-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_invoice_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_product',
            field=models.ImageField(default='static/sales/', upload_to='static/sales/'),
        ),
    ]
