# Generated by Django 4.1.2 on 2022-11-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_product_photo_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_product',
        ),
    ]
